FROM maven:3.6.3-jdk-11

WORKDIR /usr/src/app

COPY pom.xml /usr/src/app/
COPY ./scr/test/java /usr/scr/app/scr/test/java

# commend for the terminal to download docker $docker build -t karatetest .

# $docker run -it karatetest





